version: "3.7"

services:

  caddy:
    image: caddy:2.6.4
    container_name: phase-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${PWD-.}/docker/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD-.}/src:/src

  mysql:
    image: mysql:5.7
    container_name: phase-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=phase
      - MYSQL_USER=phase
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"

  php-fpm:
    build:
      context: ${PWD-.}
      dockerfile: docker/php-fpm/Dockerfile
    container_name: phase-php-fpm
    working_dir: /src
    volumes:
      - ${PWD-.}/src:/src